'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  BookOpen, 
  Target, 
  FileQuestion, 
  Bookmark, 
  Copy, 
  RefreshCw,
  Plus,
  ExternalLink,
  ChevronDown,
  Download
} from 'lucide-react';
import { Button, Card, Badge } from '@/components/ui';
import { cn } from '@/lib/utils';
import { toast } from 'react-hot-toast';

export function StudyTools({ paper }: { paper: any }) {
  const [activeTab, setActiveTab] = useState('summary');
  const [expandedQuestion, setExpandedQuestion] = useState<number | null>(null);

  const tabs = [
    { id: 'summary', icon: BookOpen, label: 'Summary' },
    { id: 'topics', icon: Target, label: 'Topics' },
    { id: 'exams', icon: FileQuestion, label: 'Exams' },
    { id: 'saved', icon: Bookmark, label: 'Saved' },
  ];

  return (
    <aside className="w-[320px] bg-[#0D0D14] border-l border-border-accent flex flex-col h-full overflow-hidden">
      {/* Tabs Header */}
      <div className="flex border-b border-border-accent">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              "flex-1 py-4 flex flex-col items-center justify-center gap-1 transition-all relative group",
              activeTab === tab.id ? "text-primary" : "text-muted hover:text-foreground"
            )}
          >
            <tab.icon size={18} />
            <span className="text-[9px] font-black uppercase tracking-widest">{tab.label}</span>
            {activeTab === tab.id && (
              <motion.div 
                layoutId="tool-tab-active" 
                className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary shadow-glow" 
              />
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-y-auto p-5 custom-scrollbar">
        <AnimatePresence mode="wait">
          {activeTab === 'summary' && (
            <motion.div 
              key="summary"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="space-y-6"
            >
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-black uppercase tracking-widest text-muted">AI Summary</h3>
                  <button className="text-[10px] font-bold text-primary hover:underline flex items-center gap-1 uppercase tracking-widest">
                    <RefreshCw className="w-3 h-3" /> Regenerate
                  </button>
                </div>
                <Card className="bg-surface-2 border-primary/20">
                  <p className="text-sm leading-relaxed italic text-foreground/90">
                    {paper.summary || "Summary is being generated by AI..."}
                  </p>
                </Card>
                <Button variant="secondary" size="sm" className="w-full h-10 text-[10px] uppercase font-bold">
                  <Copy className="w-3.5 h-3.5 mr-2" /> Copy to Clipboard
                </Button>
              </div>
            </motion.div>
          )}

          {activeTab === 'topics' && (
            <motion.div 
              key="topics"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="space-y-4"
            >
              {(paper.key_topics || []).map((topicItem: any, i: number) => {
                const topicName = typeof topicItem === 'string' ? topicItem : topicItem.topic;
                const topicDesc = typeof topicItem === 'string' ? 'Click to explain in detail' : topicItem.description;
                
                return (
                  <button
                    key={i}
                    className="w-full p-4 bg-surface-2 border border-border-accent rounded-xl text-left hover:border-primary/50 transition-all group"
                    onClick={() => window.dispatchEvent(new CustomEvent('send-chat-message', { 
                      detail: `Explain ${topicName} in detail from this paper.` 
                    }))}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-sm font-bold text-foreground">{topicName}</p>
                      <Plus className="w-3.5 h-3.5 text-muted group-hover:text-primary" />
                    </div>
                    <p className="text-[10px] text-muted font-medium line-clamp-2">{topicDesc}</p>
                  </button>
                );
              })}
            </motion.div>
          )}

          {activeTab === 'exams' && (
            <motion.div 
              key="exams"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="space-y-4"
            >
              <h3 className="text-xs font-black uppercase tracking-widest text-muted mb-4">Predicted Questions</h3>
              {(paper.exam_questions || []).map((qItem: any, i: number) => {
                const questionText = typeof qItem === 'string' ? qItem : qItem.question;
                const answerText = typeof qItem === 'string' ? "Thinking... Generating optimized answer based on university syllabus." : qItem.answer;
                const marks = typeof qItem === 'object' ? qItem.marks : null;

                return (
                  <div key={i} className="space-y-2">
                    <button 
                      onClick={() => setExpandedQuestion(expandedQuestion === i ? null : i)}
                      className="w-full p-4 bg-surface-2 border border-border-accent rounded-xl text-left hover:border-primary/50 transition-all group flex items-start gap-3"
                    >
                      <span className="text-xs font-black text-primary mt-0.5">Q{i+1}</span>
                      <div className="flex-1">
                        <span className="text-xs font-bold block">{questionText}</span>
                        {marks && <span className="text-[9px] text-muted font-bold uppercase tracking-wider mt-1 block">[{marks} Marks]</span>}
                      </div>
                      <ChevronDown className={cn("w-4 h-4 text-muted transition-transform", expandedQuestion === i && "rotate-180")} />
                    </button>
                    {expandedQuestion === i && (
                      <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="overflow-hidden">
                        <div className="p-4 bg-primary/5 border border-primary/20 rounded-xl">
                          <p className="text-[10px] font-black uppercase tracking-widest text-primary mb-2">Model Answer</p>
                          <p className="text-xs leading-relaxed text-muted">{answerText}</p>
                          <div className="flex gap-2 mt-4">
                            <Button size="sm" variant="ghost" className="h-7 text-[8px] font-black uppercase tracking-widest" onClick={() => {
                              window.dispatchEvent(new CustomEvent('save-qa', { detail: { question: questionText, answer: answerText } }));
                            }}>
                              <Bookmark className="w-3 h-3 mr-1" /> Save Q&A
                            </Button>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </div>
                );
              })}
              <Button variant="secondary" className="w-full h-10 text-[10px] font-black uppercase mt-4">
                Generate 5 More
              </Button>
            </motion.div>
          )}

          {activeTab === 'saved' && (
            <motion.div 
              key="saved"
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="space-y-4"
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xs font-black uppercase tracking-widest text-muted">Saved Q&As</h3>
                <Button size="sm" variant="ghost" className="h-8 text-[9px] font-bold uppercase tracking-widest">
                  <Download className="w-3 h-3 mr-1.5" /> Export PDF
                </Button>
              </div>
              
              <div className="py-20 text-center space-y-4 opacity-50">
                <Bookmark className="w-10 h-10 mx-auto text-muted" />
                <p className="text-xs font-bold uppercase tracking-widest">No saved questions yet</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </aside>
  );
}
